Fix filter with meta key error
With filter like `any(some_meta_name:"^value$")` (which happens when
clicking on a meta value in the entry list), it results in error:

```
  File "<...>/lib/python3.8/site-packages/fava/core/filters.py", line 279, in _key
    if key in entry.meta:
TypeError: argument of type 'NoneType' is not iterable
```

This is due to postings having metadata only as an optional property.

Close #1199