Consider leap years for FYE 02-28
A FYE of 02-28 would lead to the following error for certain years:

        return start_date, start_date.replace(year=start_date.year + 1)
    ValueError: day is out of range for month

This is because the start_date was incorrectly calculated as 2016-02-29
(instead of 2016-03-01) but 2017-02-29 (start_date plus a year) doesn't
exist.

Fixes #911